name: car
channels:
  - conda-forge
dependencies:
- python
- numpy
- pip
- numpy
- scipy
- matplotlib
- sympy
- ipython
- ipykernel
- ipyvtklink
- nbconvert
- pandas
- panel
- scikit-learn
- cma
- cadquery
- flask
- ipyvolume
- fvcore
- iopath
- plotly
- pywin32
- quaternion
pip:
  - git+https://github.com/gumyr/build123d --user
  - git+https://github.com/meadiode/cq_gears.git@main --user
  - git+https://github.com/gumyr/cq_warehouse.git#egg=cq_warehouse --user
  - ocp_tessellate webcolors cadquery-massembly ocp_vscode requests orjson urllib3 certifi